# Generated by Django 6.0.7 on 2026-07-20 18:36

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='El CI debe tener exactamente 11 dígitos numéricos', regex='^\\d{11}$')], verbose_name='Carnet de Identidad')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apell1', models.CharField(max_length=80, verbose_name='Apellido 1')),
                ('apell2', models.CharField(max_length=80, verbose_name='Apellido 2')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CU', verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
