# Generated by Django 6.0.7 on 2026-07-20 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('refraccion', models.CharField(blank=True, default='', max_length=100)),
                ('ojo_derecho', models.CharField(blank=True, default='', max_length=100)),
                ('ojo_izquierdo', models.CharField(blank=True, default='', max_length=100)),
                ('add', models.CharField(blank=True, default='', max_length=50)),
                ('galenos', models.CharField(blank=True, default='', max_length=100)),
                ('corta_y_monta', models.CharField(blank=True, default='', max_length=100)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='paciente.paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-created'],
            },
        ),
    ]
